server {
    listen 4208;

    # Definir o diretório raiz para os arquivos estáticos do Angular
    root /usr/share/nginx/html;
    index index.html;

    # Configuração para que o Nginx sempre sirva o index.html
    # em caso de rotas do Angular (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuração de cache para melhorar o desempenho
    location ~* \.(?:manifest|json|css|js|map|ico|png|jpg|jpeg|gif|svg|webp)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}